### ISSUE TITLE
CPLEX Mac installer fails in Big Sur!

### ISSUE THREAD

**Issue by hessamolya** [IBMDecisionOptimization/Decision-Optimization-with-CPLEX-samples#4]
The Mac CPLEX installer just creates a log file. Is there any way to resolve the issue? Someone else asked this question here:

https://www.ibm.com/mysupport/s/question/0D53p00008IulS3/macos-installer-vor-cplex-2010-not-working

Here is a part of the log file.

Installation: Unsuccessful.

0 Successes
0 Warnings
0 NonFatalErrors
1 FatalErrors

Action Notes:

None

Install Log Detail:

Product Installer:        
                          Status: FATAL ERROR
                          Additional Notes: FATAL ERROR - The installer has failed due to an unhandled exception
                                            java.awt.IllegalComponentStateException: The frame is decorated

**Comment by vlkong** [comment]
Hi,

It looks like the installer has issues with MacOS darkmode, and that if you first switch to lightmode, it works.
https://community.ibm.com/community/user/datascience/communities/community-home/digestviewer/viewthread?MessageKey=1e453851-3c50-4c72-83a9-8c7f05df8810&CommunityKey=ab7de0fd-6f43-47a9-8261-33578a231bb7&tab=digestviewer#bm1e453851-3c50-4c72-83a9-8c7f05df8810

Can you please give this a try ?

Thanks

**Comment by vlkong** [comment]
Closing issue as there is no news
