### ISSUE TITLE
Finding extreme rays in an LP

### ISSUE THREAD

**Issue by amirvaez** [IBMDecisionOptimization/Decision-Optimization-with-CPLEX-samples#6]
Hello,

I am writing a code for Benders' algorithm and in one part, I need to know what are the extreme rays of the problem ( directions or answers which may result in unbounded solution). Is there any prompt, command or sample code to find such direction in IBM doclpex?

I would really appreciate if you could help me in this regards,

Best, 
Amir

**Comment by PhilippeCouronne** [comment]
Hello,

Here is a simple code which extracts unbounded rays from an infeasible model.
[unbounded_ray.zip](https://github.com/IBMDecisionOptimization/Decision-Optimization-with-CPLEX-samples/files/6183599/unbounded_ray.zip)

Regards.

    Philippe

**Comment by amirvaez** [comment]
Thank you Philliope for your prompt response. I will write this code according to my model and will get back to you if I have questions.

Thank you very much,

Best,

Amir


Amirhossein Vaeztehrani,  Ph.D. candidate,

Department of Management Sciences,

University of Waterloo

________________________________
